@Web_HostAddress = http://localhost:5209
 
GET {{Web_HostAddress}}/api/product/all
Accept: application/json

###
POST {{Web_HostAddress}}/api/user/login
Content-Type: application/json

{
    "email": "chismaquis@gmail.com",
    "password": "index"
}